#!/usr/bin/env python3
"""Write a synthetic session set for documentation renders.

The README needs a picture of the app, not a picture of somebody's afternoon.
Every project here is invented, so the images can be regenerated by anyone
without exposing whatever they happen to be working on.

Chosen to exercise the row layout rather than to look tidy: both providers,
all three states, two different parent directories (so the location field is
visibly doing something), and one worktree session whose generated branch name
is long enough to be shortened.

Usage: demo-sessions.py <dir>   # <dir> becomes AGENT_TRACKER_DIR
"""

import json
import pathlib
import shutil
import sys
from datetime import datetime, timedelta, timezone

# provider, cwd, state, reason, minutes ago
DEMO = [
    (
        "claude-code",
        "/Users/dev/acme/checkout-service",
        "needsYou",
        "Turn complete — ready for you",
        2,
    ),
    ("codex", "/Users/dev/acme/design-system", "needsYou", "Needs your attention", 11),
    ("claude-code", "/Users/dev/oss/api-gateway", "running", "Using Bash", 0),
    (
        "claude-code",
        (
            "/Users/dev/acme/billing-api/.claude/worktrees/"
            "alice-app-123-fix-checkout-redirect-loop-on-expired-session-8419e2f7"
        ),
        "running",
        "Working…",
        0,
    ),
    ("codex", "/Users/dev/oss/docs-site", "idle", "Seen", 47),
]


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    root = pathlib.Path(sys.argv[1])
    shutil.rmtree(root, ignore_errors=True)
    sessions = root / "sessions"
    sessions.mkdir(parents=True)

    now = datetime.now(timezone.utc)
    for provider, cwd, state, reason, age in DEMO:
        moment = (now - timedelta(minutes=age)).strftime("%Y-%m-%dT%H:%M:%SZ")
        name = pathlib.PurePath(cwd).name
        # No `pid`: the store prunes any session whose recorded pid is not
        # alive, and a fixture has no process behind it.
        payload = {
            "schema": 1,
            "provider": provider,
            "sessionId": f"demo-{name}",
            "cwd": cwd,
            "state": state,
            "reason": reason,
            "stateChangedAt": moment,
            "updatedAt": moment,
            "termProgram": "ghostty",
        }
        path = sessions / f"{provider}-demo-{name}.json"
        path.write_text(json.dumps(payload, indent=2, sort_keys=True))

    print(f"{len(DEMO)} demo session(s) -> {sessions}")


if __name__ == "__main__":
    main()
