#!/usr/bin/env python3
"""Write a synthetic session set for documentation renders.

The README needs a picture of the app, not a picture of somebody's afternoon.
Every project here is invented, so the images can be regenerated by anyone
without exposing whatever they happen to be working on.

Chosen to exercise the row layout rather than to look tidy: all three states,
two sessions sharing one repo (so the disambiguating names show), two different
parent directories (so the location field is visibly doing something), and one
worktree session whose generated branch name is long enough to be shortened.

Usage: demo-sessions.py <dir> [claude-dir]
       <dir> becomes AGENT_TRACKER_DIR, [claude-dir] AGENT_TRACKER_CLAUDE_DIR
"""

import json
import pathlib
import shutil
import sys
from datetime import datetime, timedelta, timezone

# cwd, state, reason, minutes ago
DEMO = [
    (
        "/Users/dev/acme/checkout-service",
        "needsYou",
        "Turn complete — ready for you",
        2,
    ),
    ("/Users/dev/acme/design-system", "needsYou", "Approve Bash?", 11),
    ("/Users/dev/oss/api-gateway", "running", "Using Bash", 0),
    ("/Users/dev/oss/api-gateway", "needsYou", "Approve Edit?", 4),
    (
        (
            "/Users/dev/acme/billing-api/.claude/worktrees/"
            "alice-app-123-fix-checkout-redirect-loop-on-expired-session-8419e2f7"
        ),
        "running",
        "Working…",
        0,
    ),
    ("/Users/dev/oss/docs-site", "idle", "Seen", 47),
]


def main():
    if not 2 <= len(sys.argv) <= 3:
        sys.exit(__doc__)
    root = pathlib.Path(sys.argv[1])
    claude_root = pathlib.Path(sys.argv[2]) if len(sys.argv) == 3 else None
    shutil.rmtree(root, ignore_errors=True)
    sessions = root / "sessions"
    sessions.mkdir(parents=True)

    now = datetime.now(timezone.utc)
    registry = []
    for index, (cwd, state, reason, age) in enumerate(DEMO):
        moment = (now - timedelta(minutes=age)).strftime("%Y-%m-%dT%H:%M:%SZ")
        name = pathlib.PurePath(cwd).name
        session_id = f"demo-{name}-{index:02d}"
        # No `pid`: the store prunes any session whose recorded pid is not
        # alive, and a fixture has no process behind it.
        payload = {
            "schema": 1,
            "provider": "claude-code",
            "sessionId": session_id,
            "cwd": cwd,
            "state": state,
            "reason": reason,
            "stateChangedAt": moment,
            "updatedAt": moment,
            "termProgram": "ghostty",
        }
        path = sessions / f"claude-code-{session_id}.json"
        path.write_text(json.dumps(payload, indent=2, sort_keys=True))
        registry.append(
            {
                "sessionId": session_id,
                "cwd": cwd,
                # Claude's own slug for the session. Only surfaces on rows the
                # project name cannot tell apart, which here is api-gateway.
                "name": f"{name}-{session_id[-2:]}",
            }
        )

    # The usage strip reads Claude's quota from the statusline payload, so
    # without one the README would picture a dropdown missing a row it now
    # always has. Invented numbers, chosen to sit below every warning threshold
    # so the picture shows the resting state rather than an alarm.
    #
    # The same payload carries per-session context pressure, and this is where
    # the fixture has to respect a real constraint rather than fake past it: one
    # file holds ONE session's payload, so two sessions can only both have a
    # reading if they come from the two different sources the app reads. That is
    # exactly how it works on a real machine.
    resets_at = int((datetime.now(timezone.utc) + timedelta(hours=2)).timestamp())
    statusline = {
        "session_id": "demo-checkout-service-00",
        # Past the urgent threshold, so the picture shows the colour that means
        # "finish this thought" rather than only the mild one.
        "context_window": {"used_percentage": 92},
        "rate_limits": {
            "five_hour": {"used_percentage": 38, "resets_at": resets_at},
            "seven_day": {"used_percentage": 49, "resets_at": resets_at + 5 * 86400},
        },
    }
    (root / "claude-statusline.json").write_text(
        json.dumps(statusline, indent=2, sort_keys=True)
    )

    if claude_root is not None:
        claude_root.mkdir(parents=True, exist_ok=True)
        registry_dir = claude_root / "sessions"
        registry_dir.mkdir(parents=True, exist_ok=True)
        for index, entry in enumerate(registry):
            (registry_dir / f"{9000 + index}.json").write_text(
                json.dumps(entry, indent=2, sort_keys=True)
            )
        (claude_root / "statusline-last.json").write_text(
            json.dumps(
                {
                    "session_id": "demo-api-gateway-02",
                    "context_window": {"used_percentage": 76},
                },
                indent=2,
                sort_keys=True,
            )
        )

    print(f"{len(DEMO)} demo session(s) -> {sessions}")


if __name__ == "__main__":
    main()
